# Generated by Django 3.0.7 on 2021-02-06 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0002_auto_20210206_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch_start_year',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='batch',
            name='semester',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='batch_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Batch'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='batch_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.Batch'),
        ),
    ]
