# Generated by Django 3.0.7 on 2021-02-06 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0003_auto_20210206_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='updated_at',
        ),
    ]
