# Generated by Django 3.0.7 on 2021-02-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_department_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default=1, max_length=255, unique=True),
        ),
    ]
