# Generated by Django 3.1 on 2020-12-08 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_auto_20201207_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentresult',
            old_name='lab_Marks',
            new_name='lab',
        ),
        migrations.RenameField(
            model_name='studentresult',
            old_name='selfstudy_marks',
            new_name='selfstudy',
        ),
    ]
