# Generated by Django 3.1 on 2020-12-09 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0008_auto_20201208_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.batch'),
        ),
        migrations.AlterField(
            model_name='students',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.batch'),
        ),
    ]
