# Generated by Django 3.1 on 2020-12-09 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0009_auto_20201209_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='batch_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.batch'),
        ),
    ]
