# Generated by Django 3.1 on 2020-12-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0010_auto_20201209_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='student_management_app.batch'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_management_app.students'),
        ),
    ]
