# Generated by Django 3.1 on 2020-12-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0011_auto_20201209_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='dept_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='student_management_app.department'),
        ),
    ]
