# Generated by Django 3.1 on 2020-12-26 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0012_staffs_dept_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='gender',
            field=models.CharField(default='Male', max_length=50),
        ),
    ]
