# Generated by Django 3.1 on 2020-12-26 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0013_staffs_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='phn_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='students',
            name='phn_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subjects',
            name='batch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='student_management_app.batch'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='credit',
            field=models.IntegerField(default=0),
        ),
    ]
