# Generated by Django 3.1 on 2020-12-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0015_auto_20201226_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjects',
            name='cid',
            field=models.CharField(default='Pls Enter', max_length=8),
        ),
    ]
